# Generated by Django 6.0.2 on 2026-04-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_department_professor_prof_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='publication',
            name='publish_year',
            field=models.IntegerField(default=2026),
        ),
    ]
